import type { Metadata } from "next";
import { Sora } from "next/font/google";
import "./globals.css";
import ResponsiveNav from "./Components/Home/Navbar/ResponsiveNav";
import Footer from "./Components/Home/Footer/Footer";
import ScrollToTop from "./Components/Helper/ScrollToTop";

const font = Sora({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800',],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="custom-scroll scroll-smooth cursor-default">
      <body className={font.className}>
        <ResponsiveNav />
        {children}
        <Footer/>
        <ScrollToTop/>

      </body>
    </html>
  );
}
